export const fuels = [
  {
    label: "Yakıt Tipi",
    value: "",
  },
  {
    label: "Gaz",
    value: "Gas",
  },
  {
    label: "Elektik",
    value: "Electricity",
  },
  {
    label: "Dizel",
    value: "Diesel",
  },
];
export const years = [
  { label: "Yıl", value: "" },
  { label: "2015", value: "2015" },
  { label: "2016", value: "2016" },
  { label: "2017", value: "2017" },
  { label: "2018", value: "2018" },
  { label: "2019", value: "2019" },
  { label: "2020", value: "2020" },
  { label: "2021", value: "2021" },
  { label: "2022", value: "2022" },
  { label: "2023", value: "2023" },
];

export const makes = [
  "Acura",
  "Alfa Romeo",
  "Aston Martin",
  "Audi",
  "Bentley",
  "BMW",
  "Buick",
  "Cadillac",
  "Chevrolet",
  "Chrysler",
  "Dodge",
  "Ferrari",
  "Fiat",
  "Ford",
  "GMC",
  "Honda",
  "Hyundai",
  "Infiniti",
  "Jaguar",
  "Jeep",
  "Kia",
  "Lamborghini",
  "Land Rover",
  "Lexus",
  "Lincoln",
  "Maserati",
  "Mazda",
  "McLaren",
  "Mercedes-Benz",
  "MINI",
  "Mitsubishi",
  "Nissan",
  "Porsche",
  "Ram",
  "Rolls-Royce",
  "Subaru",
  "Tesla",
  "Toyota",
  "Volkswagen",
  "Volvo",
];

export const colors = [
  "pspc0124",
  "pspc0034",
  "pspc0002sspc0391",
  "pspc0145",
  "pspc0103sspc0015",
  "pspc0197sspc0014",
  "pspc0209",
  "pspc0103",
  "pspc0020",
];
